---
- name: "Ensure the '{{ docker_base_path }}' directory exists"
  ansible.builtin.file:
    path: "{{ docker_base_path }}"
    state: "directory"
    mode: "0755" # Allow user, group, and others to access the directory.

- name: "Copying the application's file to the target at: '{{ app_path }}'"
  ansible.builtin.copy:
    src: "docker/"
    dest: "{{ app_path }}"
    mode: "preserve"

- name: "Copying the application's SSL Certificate to the target"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "preserve"
  loop: "{{ certificates | default([]) }}"

- name: "Ensuring the directories that Minio will use exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    mode: "0755"
  loop:
    - "/mnt/data"

- name: "Creating and starting services (docker-compose up)"
  community.docker.docker_compose_v2:
    project_name: "storage"
    project_src: "{{ app_path }}"
    # This will apply changes without restarting the containers unnecessarily.
    state: "present"
