---
# Base directory for Docker-related files on the target host
docker_base_path: "/opt/docker"

# Path to the application directory, derived from the base Docker path
app_path: "{{ docker_base_path }}/minio"

# Destination path where SSL certificates will be copied on the target host
certificates_dest_path: "{{ app_path }}/certificates"

# Base source directory where certificates are stored on the control node
certificates_base_path: "/opt/certificates"

# Path to the certificate of the application
certificate_path: "{{ certificates_base_path }}/edge-storage.lan.homelab"

# List of certificates to copy to the target host (includes CA and storage certs)
certificates:
  - { src: "{{ certificate_path }}/edge-storage.lan.homelab.crt", dest: "{{ certificates_dest_path }}/public.crt" }
  - { src: "{{ certificate_path }}/edge-storage.lan.homelab.key", dest: "{{ certificates_dest_path }}/private.key" }
