# Define the services to be deployed
services:
  # MinIO service configuration
  minio:
    # Use the custom MinIO image from a private registry
    image: "minio/minio:latest"

    # Name of the container
    container_name: "minio"

    # Restart policy for the container
    restart: "unless-stopped"

    # Environment variables for MinIO configuration
    environment:
      # Path of the config file
      - "MINIO_CONFIG_ENV_FILE=/etc/minio/config"
      # Root password for MinIO, fetched from environment variables
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"

    # Expose ports for the Web UI and API.
    ports:
      # API
      - "9000:9000"
      # Web console
      - "9001:9001"

    # Mount volumes into the container
    volumes:
      # Ensure container uses the host's timezone settings
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      # Mount the MinIO configuration file directory
      - "./config/minio:/etc/minio/config:ro"
      # Mount certificates
      - "./certificates/:/etc/minio/certs/"
      # Mount directories for data storage
      - "/mnt/data:/data"

    # Command to start the MinIO server with API and Web console ports
    command: "minio server --address :9000 --console-address :9001 --certs-dir /etc/minio/certs/"

    # Health check configuration to ensure the container is healthy
    # healthcheck:
    #   # Command to check if MinIO is ready using mc (MinIO client)
    #   test: ["CMD", "mc", "ready", "local"]
    #   # Time to wait before starting the health checks
    #   start_period: "5s"
    #   # Interval between health checks
    #   interval: "10s"
    #   # Timeout for each health check
    #   timeout: "2s"
    #   # Number of retries before marking the container as unhealthy
    #   retries: 2
