---
- name: "Importing DNS entries setup playbook"
  ansible.builtin.import_playbook: "firewall.yml"

- name: "Importing initial settings setup playbook for the virtual machine"
  ansible.builtin.import_playbook: "setup_vm.yml"

- name: "Importing application setup playbook"
  ansible.builtin.import_playbook: "setup_app.yml"
